### ISSUE TITLE
landing page doesn't build on ubuntu 24.04

### ISSUE THREAD

**Issue by cazitouni** [elpaso/qgis-server-landing-page-plugin#41]
Hello,

After installing a new instance of QGIS Server on a fresh Ubuntu installation, I noticed that the landing page did not seem to build a version in:

/usr/share/qgis/resources/server/api/ogc/static/landingpage/

This occurred despite the plugin package being installed correctly via apt.

As a result, I encountered an error stating that index.html could not be found, after following the installation tutorial in [the documentation](https://docs.qgis.org/3.34/en/docs/server_manual/getting_started.html#installation-on-debian-based-systems).

After building a local copy and creating a symlink to the folder mentioned above, it works fine.

I’m not sure if you are aware of this issue. Let me know.

Regards,
Clément

**Comment by elpaso** [comment]
see: https://github.com/qgis/QGIS/issues/55462
