### ISSUE TITLE
Add some notes about the status of this repository ?

### ISSUE THREAD

**Issue by Gustry** [elpaso/qgis-server-landing-page-plugin#6]
Hi,

Following the discussion on the QGIS-Dev mailing list, it might be indeed a little bit confusing if the landing page is still a plugin or not. I see this plugin got some commits since the release of the 3.16.

Is this repo required for QGIS >= 3.16 ? Or is-it only for < 3.16 ?
Maybe some notes can be added in the readme ? (or make it deprecated at some points ?)

Thanks for this work. Feel free to close this ticket if it's not relevant.

**Comment by pathmapper** [comment]
> Is this repo required for QGIS >= 3.16

Not required, but 
>for local development, the https://github.com/elpaso/qgis-server-landing-page-plugin still provides the landing page as a Python plugin, it is very convenient but you need to disable the core landing page, there is an env var to do that.

from https://github.com/qgis/QGIS/pull/38189#commitcomment-43909827

**Comment by elpaso** [comment]
The source code of the client js part is now in QGIS main repo (I had to do it myself, of course: people is good for asking but not for doing).

So, technically this repo is not needed anymore but I'd like to keep it live for development purposes.
